name: Continuous Integration for Scala
on:
  pull_request:
    branches:
      - master
  release:
    types:
      - created
jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        os: [ubuntu-latest]
        scala: [3.2.0]
        java: [11]

    defaults:
      run:
        working-directory: scala

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java and Scala
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'sbt'

      - name: Cache scala dependencies
        uses: coursier/cache-action@v6

      - name: Run tests
        run: sbt ++${{ matrix.scala }} test
